[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "xg6ahsH0Vrk7oRmWOVFKSWeaLNOs56d54w3Xg//p1OY="

[auth.keycloak]
client_id = "LEX_LOCAL_ENV"
client_secret = "O1dT6TEXjsQWbRlzVxjwfUnNHPnwDmMF"
server_metadata_url = "https://exc-testing.com/realms/lex/.well-known/openid-configuration"
client_kwargs = { "verify" = false, "scope" = "openid profile email offline_access" }
