name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "00 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.0]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: lundadminlocal
          POSTGRES_DB: db_lex
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependecies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --prefer-binary -r requirements.txt
      - name: Save pip cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Run Tests
        run: |
          cd lex
          coverage run --source='.' manage.py test --parallel --verbosity=2
          coveage report
